### ISSUE TITLE
[(cv2.Rodrigues(pp)[0] - np.eye(3)).ravel() TypeError: Expected Ptr<cv::UMat> for argument 'src'

### ISSUE THREAD

**Issue by He-Chao** [LyuJ1998/HandTailor#11]
Hi, When I use python demo.py, this error came up
![Screenshot from 2022-01-11 16-22-02](https://user-images.githubusercontent.com/38954558/148906481-657d44d8-f1e5-4933-ae8d-d71ff2891064.png)

**Comment by LyuJ1998** [comment]
Hi, thank you for mention this! 
I have update the code in `manolayer.py`, the problem should be fixed.

**Comment by He-Chao** [comment]
您好,我是何超.我已收到您的邮件。  如有需要我将尽快给您回复，谢谢！若您有急事,请电话或短信我。

**Comment by He-Chao** [comment]
您好,我是何超.我已收到您的邮件。  如有需要我将尽快给您回复，谢谢！若您有急事,请电话或短信我。
