### ISSUE TITLE
Joints' indeces clarification

### ISSUE THREAD

**Issue by OlafenwaMoses** [LyuJ1998/HandTailor#12]
Great work you have done with this research @LyuJ1998 . I just have a question on the joint's location converted [here from uvd to xyz](https://github.com/LyuJ1998/HandTailor/blob/454060395effa234f97b0daacccff2ad8c131623/utils.py#L66);

- What is the index for each joint in the converted locations?

**Comment by LyuJ1998** [comment]
Hi, thanks for your interest in our work!
I think you can find out the index for each joint through this, in which each joint appears in order
![kp](https://user-images.githubusercontent.com/31683380/155126958-63a85eb6-4e11-41a2-94df-ca6e48f3d424.gif)

**Comment by OlafenwaMoses** [comment]
Awesome. That clarifies it. Thanks for the quick response. Keep up the good work.
