### ISSUE TITLE
Running with webcam

### ISSUE THREAD

**Issue by arjun-98** [LyuJ1998/HandTailor#15]
Is it possible to run app_in_the_wild.py without using a Real Sense camera? As in is it possible to simply connect the webcam of the laptop?

**Comment by LyuJ1998** [comment]
Yes, you can run Handtailor with any kind of RGB camera, just replace the `RealSenseCapture` class in `app_in_the_wild` with your own webcam wrapper.

**Comment by arjun-98** [comment]
Thank you very much!
