### ISSUE TITLE
Could the code run with normal webcam ?

### ISSUE THREAD

**Issue by Stephenfang51** [LyuJ1998/HandTailor#16]
as the titled said. Thanks !

**Comment by LyuJ1998** [comment]
Yes, any kind of webcam should be okay, only RGB image and camera parameter (optional) are required.

**Comment by Stephenfang51** [comment]
@LyuJ1998  谢谢回复，但我昨天尝试了每一个脚本都有报错哈哈， 比如demo.py这个，报的
```
AttributeError: 'ColoredRenderer' object has no attribute 'vbo_verts_face'
```
然后是demo_in_the_wild.py
报的是
```
TypeError: '<class 'jaxlib.xla_extension.DeviceArray'>' object does not support item assignment. JAX arrays are immutable. Instead of ``x[idx] = y``, use ``x = x.at[idx].set(y)`` or another .at[] method: https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.at.html
```

你能告诉我哪一个适合webcam,直接运行， 先不考虑内参的设置吗 谢谢你的快速回复！

**Comment by LyuJ1998** [comment]
不考虑内参用`demo_in_the_wild.py`。如果按照readme中步骤配置环境应该可以正常运行。你用的jax版本是多少？

**Comment by LyuJ1998** [comment]
```AttributeError: 'ColoredRenderer' object has no attribute 'vbo_verts_face'```
这个可能是因为opendr版本不对导致的。

**Comment by XIANGLINYUN** [comment]
> Author
我也遇到了的同样的错误，请问解决了吗

**Comment by LyuJ1998** [comment]
@XIANGLINYUN 什么问题？
