### ISSUE TITLE
Can I only use Hand Module without IkNet to 3D hand Pose Estimation

### ISSUE THREAD

**Issue by Rookienovice** [LyuJ1998/HandTailor#17]
你好，请问可以用您论文中去除 IkNet 的Hand Module去做三维姿态的估计吗，我尝试使用您论文中提到 公式（6）损失去训练网络，用热力图监督二维坐标，用21点3D pose监督uvd2xyz后的3D坐标，用根关节点的值监督root，最终效果不好，请问我这样的作法对吗？
![image](https://user-images.githubusercontent.com/35412397/173828812-ee15db28-d927-49b2-b674-efb4b15fef10.png)

**Comment by LyuJ1998** [comment]
效果不好体现在哪些方面？根节点root相对相机的深度的预测可能会效果很差，root-relative scale-normalized的pose预测应该并不难。

**Comment by Rookienovice** [comment]
感谢您这么快的回复！ 效果不好体现在MPJPE指标上，uvd2xyz后的joint 和 groundtruth差别很大，和 并且我观察到网络预测出的joint，经计算后得到的 root-relative scale-normalized pose 和 ground-truth 的 root-relative scale-normalized pose也不匹配，
![image](https://user-images.githubusercontent.com/35412397/173841223-64076c7e-0730-47d9-898a-9e604baccd3e.png)

**Comment by Rookienovice** [comment]
不知道我理解的对不对，Hand Module without IKNet 预测的是像素平面的uv坐标 和 根相对归一化z坐标，然后通过相机参数转化为相机空间中的三维坐标，网络通过直接监督uv（以heatmap的形式），uvd2xyz计算出3D pose 和 3D pose root 训练的。

**Comment by LyuJ1998** [comment]
2d keypoint可视化出来有问题吗？
你试试训练的时候3d pose root不要用预测，直接用GT会是什么效果。

**Comment by Rookienovice** [comment]
2d KP的可视化也有不小误差，对自遮挡严重的效果就更差了
![image](https://user-images.githubusercontent.com/35412397/173845810-a900faef-0063-4c9f-9398-6249239eba02.png)
![image](https://user-images.githubusercontent.com/35412397/173845859-862aeb97-20e5-4318-829b-80cc3b3f9b8e.png)

**Comment by Rookienovice** [comment]
作者您好，我在您的建议上尝试了用GT的root 和 bone 去训练了Hand Module， 最终的AUC20-50达到了0.93，效果仍然不如您论文table 1 中只使用Hand module的结果（请问你采用比较的是Hand Module 直接获得的joint还是 MANO中获得的joint），还有我想知道 如果不知道相机参数，root 和 bone的情况下，有什么方法可以直接获得相机坐标下的3d pose吗？

**Comment by LyuJ1998** [comment]
我用的是MANO得到的joint。
如果没有这些信息只有2D RGB 信息的话，个人认为理论上不太可能得到准确地相机坐标系下的3d pose。如果你的应用中获取深度图是可行的，我觉得也许还有更多的方法可以帮助你在工程上得到更为准确地3dpose？

**Comment by Rookienovice** [comment]
谢谢作者的解答，十分感谢！也就是说基于RGB图绝对的3D pose估计是很难的，一般都是估计root-relative scale-normalized的pose吗？（如果不能估计出真实的3D pose那这种pose的作用体验的哪里？） 还有请问 现在基于RGB的3D pose的方法大都是采用什么流程呢，是采用这种 分别估计 uv 和 depth，然后相机参数投影回3D空间，还是有什么别的方法？（我感觉RGB不含深度信息，那他估计出来的就是靠神经网络硬学的吗，我一直很困惑单目RGB的深度信息是怎么估计出的）

**Comment by LyuJ1998** [comment]
鉴于问题已经不是针对这个repo本身了，我觉得我们可以换个方式交流。我没法找到你的邮箱地址，如果可以的话，通过邮箱1998lvjun@gmail.com联系我~
