### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by XIANGLINYUN** [LyuJ1998/HandTailor#18]
![image](https://user-images.githubusercontent.com/103312244/180224126-293e5ab7-7337-4f15-9fe3-f17a36e2b22b.png)
我想请问为什么我在运行demo.py 之后没有任何反应呢

**Comment by LyuJ1998** [comment]
在HandTailor文件夹下创建一个out文件夹，然后运行看有没有图片被保存进去

**Comment by XIANGLINYUN** [comment]
有了，非常感谢
