### ISSUE TITLE
Depth and scale ambiguity

### ISSUE THREAD

**Issue by EAST-J** [LyuJ1998/HandTailor#19]
Hi, I try to estimate the 3D hand in the camera coordinate. I use demo.py with known intrinsic, the render result seems to be OK, but the 3D hand is not aligned with the GT.
![image](https://user-images.githubusercontent.com/51024280/232518054-f8771562-75e3-4980-ab20-0ad20b48b7f1.png)
![image](https://user-images.githubusercontent.com/51024280/232518139-82a057f4-06dd-42e6-b5f5-250ae12d4363.png)
![image](https://user-images.githubusercontent.com/51024280/232518340-8d10eaa9-832a-4522-9d58-9b53b8c8a09b.png)

**Comment by LyuJ1998** [comment]
Hi, thank you for using HandTailor. Since HandTailor only takes RGB images as inputs, it is not possible to remove the depth and scale ambiguity with only 2D information. To address this issue, I recommended using a depth map or the pose of objects to extract hand-scale information.

**Comment by EAST-J** [comment]
Thx for immediate reply.

**Comment by EAST-J** [comment]
> Hi, thank you for using HandTailor. Since HandTailor only takes RGB images as inputs, it is not possible to remove the depth and scale ambiguity with only 2D information. To address this issue, I recommended using a depth map or the pose of objects to extract hand-scale information.

Hi, sorry to bother you again. I wonder if I have a monocular RGB sequence with corresponding 2D key points, it is possible to obtain the hand mesh in the camera coordinate?
