### ISSUE TITLE
In the wild model scale error/typo

### ISSUE THREAD

**Issue by pablovela5620** [LyuJ1998/HandTailor#2]
I believe this is a typo https://github.com/LyuJ1998/HandTailor/blob/080818f66c3c8eaadd7867c4c9db093fe1c8b745/model.py#L414
where you're using the u coordinate twice instead of u-v according to this

![image](https://user-images.githubusercontent.com/25287427/111645825-7c6a6d00-87d7-11eb-8c64-393c82fc7710.png)

it should be 
```python 
s = torch.sqrt((deltaj[0,0]**2 + deltaj[0,1]**2)/(1 - deltaj[0,2]**2))
```

**Comment by LyuJ1998** [comment]
Hi, this is a typo. I have already fix this. Thank you for mention it!
