### ISSUE TITLE
Questions on optimization/tailor module

### ISSUE THREAD

**Issue by pablovela5620** [LyuJ1998/HandTailor#3]
Hiya, I had a few questions about the tailor module

Just as a high-level overview (just to make sure I correctly understand the approach). It seems that you want to refine the predicted pose parameters from the inverse kinematics network with the insight that the 2d keypoints will generally have higher accuracy/ reliability allowing for not only a more accurate prediction but also helping with bad initializations and occlusion problems in typical optimization-based techniques face (along with fewer iterations due to a good initial condition)

1. Did you experiment with different optimizers in jax other than Adam? Such as the Levenberg-Marquat solver (not sure if this is implemented in jax) used in papers like [MegaTrack](https://research.fb.com/wp-content/uploads/2020/08/MEgATrack-Monochrome-Egocentric-Articulated-Hand-Tracking-for-Virtual-Reality.pdf)/[RGB2Hands](https://handtracker.mpi-inf.mpg.de/projects/RGB2Hands/content/RGB2Hands_author_version.pdf)/[Online Optical Marker-based Hand Tracking with Deep Labels](https://research.fb.com/wp-content/uploads/2018/06/Online-Optical-Marker-based-Hand-Tracking-with-Deep-Labels.pdf)
2. For the in-the-wild examples, I've noticed certain poses lead to failure cases for estimating the scale camera parameter, is this something you've noticed as well? usually when the hand is horizontal rather than vertical

I enjoyed reading your paper greatly! Thank you so much for the contribution and I look forward to your response

**Comment by LyuJ1998** [comment]
Hi, I'm glad you discuss these questions with me.

1.  I have experimented with different optimizers in JAX, but I found Adam is the best one. As for the Levenberg-Marquat solver, I tried before, but the performance is not good, I'm not sure why. I may check it in the future.
2.  Recovery hand mesh without camera parameters can be unstable. Can you provide me some of your failure cases? I will try to find out the problems.

Thank you for this issue.

**Comment by pablovela5620** [comment]
Sorry for the late response, so I think the issue has to do with calculating the camera scale. I think it may have to do with the fact that I included a hand detector to automatically crop out a 256x256 hand and then I don't perform the refinement until AFTER doing an affine transform from crop back to the full image space. 

In the paper you mention a proof for calculating s for the `in the wild` case in the supplementary materials, but I can't seem to find them. Could you potentially provide me that link to the supp materials? So I can see what I may be doing wrong on my side.

Thanks!

**Comment by LyuJ1998** [comment]
I will upload the sipplementary materials in this repo later. But actually the proof for calculating s is quite naive. I wonder can you show me some failure cases, or, if possible, show me your code. I would like to find out the problem.

**Comment by pablovela5620** [comment]
Sure here's a gif showing the failure case. I'm not using the original iknet/keypoint estimator, rather just the optimization module provided in the codebase. So I've added a left/right hand detector, 2.5 keypoint estimator + pose/shape regressor that are my own.
![failure_case](https://user-images.githubusercontent.com/25287427/118003239-65975100-b316-11eb-9162-7de23c53461a.gif)

**Comment by LyuJ1998** [comment]
So the optimization module seems decrease the performance?

As for the proof for calculating s 
![image](https://user-images.githubusercontent.com/31683380/118012279-7631e080-b383-11eb-8846-a1677b99ab39.png)

**Comment by pablovela5620** [comment]
Yea thats what seems to be happening, BUT I think this may also be a problem of bad initialization. I'm noticing sometimes I have bad mano pose predictions from my network which could lead to a bad convergence on the optimization module. I'll do more digging. I appreciate the help and you posting the proof!
