### ISSUE TITLE
When will training code be released?

### ISSUE THREAD

**Issue by coreqode** [LyuJ1998/HandTailor#4]
Hey, this is very awesome work. Will there any training code be available soon?

**Comment by LyuJ1998** [comment]
Hi, we still not have a plan to release the training code. 

Our training code is adapted from [bihand](https://github.com/lixiny/bihand) whose owner @lixiny  is also the contributor to this work.

**Comment by coreqode** [comment]
@LyuJ1998 Thanks for quick response. So, losses are also same for all the three modules?

**Comment by LyuJ1998** [comment]
The losses are not exactly the same. You can find more details about the losses from the [paper](https://arxiv.org/abs/2102.09244).

**Comment by coreqode** [comment]
Thanks
