### ISSUE TITLE
Got weird output if using different camera intrinsics

### ISSUE THREAD

**Issue by coreqode** [LyuJ1998/HandTailor#5]
@lixiny I got pretty weird results, when used logitech c270 camera with it's intrisics. 

I used this command, 
`python demo.py --fx 1078.03779 --fy 1084.50988 --cx 580.850545 --cy 245.959325
`

I have checked the camera matrix multiple times, and it seems okay. 
Output Video link: https://drive.google.com/file/d/10oH3cL92bcvFLr1HTEfp5QOTn2WvBpVM/view?usp=sharing

**Comment by LyuJ1998** [comment]
Hi, could you please offer me some of the images captured by your camera, and tell me the original size of the image (my code would crop and resize the input image into 256*256, which may cause problems). I would like to check out this issue.

If necessary, my email 1998lvjun@gmail.com

**Comment by LyuJ1998** [comment]
Hi, there was a bug in `demo.py`, and I have already fix this. Now, given the image captured from your camera, run 
```bash
python demo.py --fx 1078.03779 --fy 1084.50988 --cx 580.850545 --cy 245.959325
```
your will get
![out](https://user-images.githubusercontent.com/31683380/115960671-5d34cd00-a545-11eb-947d-00f8546e1443.png)
 
Thank you so much for this issue!!

**Comment by coreqode** [comment]
Sure no worries. :)

**Comment by coreqode** [comment]
I think you need, one more condition like https://github.com/LyuJ1998/HandTailor/blob/233be29a02f9287889fba7591dd9011f76cee7cb/demo.py#L172 when (img.shape[0] == img.shape[1]), if image resolution is (256, 256). For this case, _cx is not already defined hence give error.

**Comment by LyuJ1998** [comment]
The problem has been fixed, thank you very much
