### ISSUE TITLE
root depth prediction question

### ISSUE THREAD

**Issue by pablovela5620** [LyuJ1998/HandTailor#8]
I'm trying to understand where you got `common.DEPTH_RANGE` and `common. DEPTH_MIN ` that are used [here](https://github.com/LyuJ1998/HandTailor/blob/eec7f2e8c8bd2c22d5ec661f8d33d3e25c33be61/utils.py#L69). In your paper you specify that you scale normalized the predicted root depth when using the perspective projection. Are these values what are used to unnormalized the predicted root depth? I may have incorrectly thought that normalization had to do with the length from the root to the MCP joint (or whatever the chosen joint was), is that not the case when predicting root depth

**Comment by LyuJ1998** [comment]
Hi, `common.DEPTH_RANGE` and `common. DEPTH_MIN` is not the normalization we mentioned in the paper. To preprocess the data, we first generate root-relative and scale-normalized joint position by set the 9th joint to 0 and the length between 0th and 9th to 1. As for `common.DEPTH_RANGE` and `common. DEPTH_MIN`, we use them to scale the range of depth map to 0~1, which is good for network training.

So, `common.DEPTH_RANGE` and `common. DEPTH_MIN` are for unormalize the depth map, obtain root-relative and scale normalized uvd coordinates. Then add the root depth and convert to xyz coordinate via camera projection model.

**Comment by pablovela5620** [comment]
That clears things up, thanks for the help
